# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/embedService.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'protos/embedService.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19protos/embedService.proto\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"\x1a\n\tTextArray\x12\r\n\x05texts\x18\x01 \x03(\t\"q\n\x10\x45mbeddingRequest\x12\r\n\x05texts\x18\x01 \x03(\t\x12\x17\n\nmax_length\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\nbatch_size\x18\x03 \x01(\x05H\x01\x88\x01\x01\x42\r\n\x0b_max_lengthB\r\n\x0b_batch_size\"\x8c\x01\n\x11\x45mbeddingResponse\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.FloatArray\x12\x11\n\x04\x63ode\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06status\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07message\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_codeB\t\n\x07_statusB\n\n\x08_message\"3\n\x0fRerankerRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x11\n\tdocuments\x18\x02 \x03(\t\"\x8b\x01\n\x10RerankerResponse\x12\x19\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0b.FloatArray\x12\x11\n\x04\x63ode\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06status\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x14\n\x07message\x18\x04 \x01(\tH\x02\x88\x01\x01\x42\x07\n\x05_codeB\t\n\x07_statusB\n\n\x08_message2w\n\x10\x45mbeddingService\x12\x32\n\tEmbedding\x12\x11.EmbeddingRequest\x1a\x12.EmbeddingResponse\x12/\n\x08Reranker\x12\x10.RerankerRequest\x1a\x11.RerankerResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.embedService_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FLOATARRAY']._serialized_start=29
  _globals['_FLOATARRAY']._serialized_end=57
  _globals['_TEXTARRAY']._serialized_start=59
  _globals['_TEXTARRAY']._serialized_end=85
  _globals['_EMBEDDINGREQUEST']._serialized_start=87
  _globals['_EMBEDDINGREQUEST']._serialized_end=200
  _globals['_EMBEDDINGRESPONSE']._serialized_start=203
  _globals['_EMBEDDINGRESPONSE']._serialized_end=343
  _globals['_RERANKERREQUEST']._serialized_start=345
  _globals['_RERANKERREQUEST']._serialized_end=396
  _globals['_RERANKERRESPONSE']._serialized_start=399
  _globals['_RERANKERRESPONSE']._serialized_end=538
  _globals['_EMBEDDINGSERVICE']._serialized_start=540
  _globals['_EMBEDDINGSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
