// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: role.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createRole = `-- name: CreateRole :one
INSERT INTO "role" (name)
VALUES ($1)
RETURNING id, name, created_at
`

func (q *Queries) CreateRole(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteRoleByName = `-- name: DeleteRoleByName :exec
DELETE FROM "role"
WHERE name = $1
`

func (q *Queries) DeleteRoleByName(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRoleByName, name)
	return err
}

const getAllRoles = `-- name: GetAllRoles :many
SELECT id, name, created_at
FROM "role"
`

func (q *Queries) GetAllRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, getAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, name, created_at
FROM "role"
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, created_at
FROM "role"
WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const updateRoleName = `-- name: UpdateRoleName :exec
UPDATE "role"
SET name = $2
WHERE id = $1
`

type UpdateRoleNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) error {
	_, err := q.db.Exec(ctx, updateRoleName, arg.ID, arg.Name)
	return err
}
