# Build stage
FROM golang:1.23.3-alpine3.20 AS builder
WORKDIR /app
COPY . .
ENV GOPROXY=https://goproxy.cn,direct 
# ENV MINIO_ACCESS_KEY=""
# ENV MINIO_SECRET_KEY=""
ENV MINIO_API_PORT=9001
ENV MINIO_HOST=localhost

RUN go mod download
RUN go build -o main main.go


# Run stage
FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/main .
ENV GIN_MODE=release
CMD [ "/app/main" ]

