# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/parser_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/parser_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/parser_service.proto\x12\x0eparser_service\":\n\x07\x44ocText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07section\x18\x02 \x01(\t\x12\x10\n\x08page_num\x18\x03 \x01(\x05\"N\n\x06\x46igure\x12\x0f\n\x07section\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x10\n\x08page_num\x18\x03 \x01(\x05\x12\x10\n\x08img_path\x18\x04 \x01(\t\"O\n\x05Table\x12\x0f\n\x07section\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ption\x18\x02 \x01(\t\x12\x10\n\x08page_num\x18\x03 \x01(\x05\x12\x12\n\ntable_html\x18\x04 \x01(\t\"^\n\x14ParseDocumentRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x03 \x01(\t\x12\x10\n\x08\x64oc_path\x18\x04 \x01(\t\"(\n\x15ParseDocumentResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\">\n\x15GetParseStatusRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x10\n\x08\x64oc_path\x18\x02 \x01(\t\"\xd9\x01\n\x16GetParseStatusResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07percent\x18\x02 \x01(\x02\x12\x13\n\x0bis_finished\x18\x03 \x01(\x08\x12\x11\n\tis_failed\x18\x04 \x01(\x08\x12&\n\x05texts\x18\x05 \x03(\x0b\x32\x17.parser_service.DocText\x12\'\n\x07\x66igures\x18\x06 \x03(\x0b\x32\x16.parser_service.Figure\x12%\n\x06tables\x18\x07 \x03(\x0b\x32\x15.parser_service.Table\"9\n\x10StopParseRequest\x12\x13\n\x0b\x62ucket_name\x18\x01 \x01(\t\x12\x10\n\x08\x64oc_path\x18\x02 \x01(\t\"$\n\x11StopParseResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2m\n\rParserService\x12\\\n\rParseDocument\x12$.parser_service.ParseDocumentRequest\x1a%.parser_service.ParseDocumentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.parser_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCTEXT']._serialized_start=47
  _globals['_DOCTEXT']._serialized_end=105
  _globals['_FIGURE']._serialized_start=107
  _globals['_FIGURE']._serialized_end=185
  _globals['_TABLE']._serialized_start=187
  _globals['_TABLE']._serialized_end=266
  _globals['_PARSEDOCUMENTREQUEST']._serialized_start=268
  _globals['_PARSEDOCUMENTREQUEST']._serialized_end=362
  _globals['_PARSEDOCUMENTRESPONSE']._serialized_start=364
  _globals['_PARSEDOCUMENTRESPONSE']._serialized_end=404
  _globals['_GETPARSESTATUSREQUEST']._serialized_start=406
  _globals['_GETPARSESTATUSREQUEST']._serialized_end=468
  _globals['_GETPARSESTATUSRESPONSE']._serialized_start=471
  _globals['_GETPARSESTATUSRESPONSE']._serialized_end=688
  _globals['_STOPPARSEREQUEST']._serialized_start=690
  _globals['_STOPPARSEREQUEST']._serialized_end=747
  _globals['_STOPPARSERESPONSE']._serialized_start=749
  _globals['_STOPPARSERESPONSE']._serialized_end=785
  _globals['_PARSERSERVICE']._serialized_start=787
  _globals['_PARSERSERVICE']._serialized_end=896
# @@protoc_insertion_point(module_scope)
