# Build stage
FROM golang:1.23.3-alpine3.20 AS builder
WORKDIR /app
COPY . .
ENV GOPROXY=https://goproxy.cn,direct 
RUN go mod download
RUN go build -o main main.go
ENV ACCESS_TOKEN_DURATION=15m
ENV REFRESH_TOKEN_DURATION=24h
ENV GIN_MODE=release

# Run stage
FROM alpine:3.20
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/db/schema /app/db/schema
COPY --from=builder /app/main .
ENV GIN_MODE=release
CMD [ "/app/main" ]

