FROM python:3.11-bullseye

WORKDIR /app
COPY . .
RUN sed -i "s@http://\(deb\|security\).debian.org@https://mirrors.aliyun.com@g" /etc/apt/sources.list

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip install -r requirements.txt --no-cache-dir --index-url https://mirrors.aliyun.com/pypi/simple/

CMD ["python", "main.py"]
