FROM python_cuda

WORKDIR /app

COPY . .

ENV REDIS_HOST=redis
ENV REDIS_PORT=6379
ENV REDIS_DB=0
ENV MAX_WORKERS=5

RUN pip install -r requirements.txt --no-cache-dir --index-url https://pypi.mirrors.ustc.edu.cn/simple/

RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxext6 libxrender-dev libgl1 ffmpeg

CMD ["/app/miniconda/envs/py311/bin/python", "main.py"]
# CMD ["tail", "-f", "/dev/null"]
